# Force Python provider detection
providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
dependsOn = ["setup"]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "python -m bot.app"
